# ======== Key bindings remaps ========
#split shortcuts; same as vim 
bind v split-window -h
bind s split-window -v
bind l list-sessions

# ------ Plugin manager -------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g status-bg black
set -g status-fg white

# Use vim-style keys in copy mode
set -g mode-keys vi

# Faster escape
set -s escape-time 0

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
